// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk4e1In1TyDwj6Zre4WyOGV6EasYHAw3c',
    appId: '1:798765806641:web:02a58ad86f6eb264a71110',
    messagingSenderId: '798765806641',
    projectId: 'final-project-db4d2',
    authDomain: 'final-project-db4d2.firebaseapp.com',
    storageBucket: 'final-project-db4d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3sJsb2rRLWF02gM4-UgQsAYENDOouBbA',
    appId: '1:798765806641:android:f50ea0aa44014dada71110',
    messagingSenderId: '798765806641',
    projectId: 'final-project-db4d2',
    storageBucket: 'final-project-db4d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXPDwNzNWZj4LaV2Zq1iK13dcLKqDqfQ0',
    appId: '1:798765806641:ios:617b763a64d72a1ba71110',
    messagingSenderId: '798765806641',
    projectId: 'final-project-db4d2',
    storageBucket: 'final-project-db4d2.firebasestorage.app',
    androidClientId: '798765806641-r0kqq7gds5nbpj5qthe22o6dpgohh5in.apps.googleusercontent.com',
    iosClientId: '798765806641-s29e59ea30ee24t097dgerr0hb7e1fgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.threadsposter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXPDwNzNWZj4LaV2Zq1iK13dcLKqDqfQ0',
    appId: '1:798765806641:ios:617b763a64d72a1ba71110',
    messagingSenderId: '798765806641',
    projectId: 'final-project-db4d2',
    storageBucket: 'final-project-db4d2.firebasestorage.app',
    androidClientId: '798765806641-r0kqq7gds5nbpj5qthe22o6dpgohh5in.apps.googleusercontent.com',
    iosClientId: '798765806641-s29e59ea30ee24t097dgerr0hb7e1fgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.threadsposter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk4e1In1TyDwj6Zre4WyOGV6EasYHAw3c',
    appId: '1:798765806641:web:4a0a1bc88d722902a71110',
    messagingSenderId: '798765806641',
    projectId: 'final-project-db4d2',
    authDomain: 'final-project-db4d2.firebaseapp.com',
    storageBucket: 'final-project-db4d2.firebasestorage.app',
  );

}